import React, { useState, useEffect } from 'react';
import { X, ShieldCheck, Lock, CreditCard, ArrowRight, CheckCircle, Sparkles, MessageCircle, AlertCircle } from 'lucide-react';
import { RealWebsite, Order } from '../types';
import { createCheckoutSession, verifyPayment, fetchSettings } from '../services/agencyApi';
import { getWhatsAppUrl } from '../data/agencyData';

interface CheckoutModalProps {
  website?: RealWebsite | null;
  customPackageName?: string;
  customAmount?: number;
  onClose: () => void;
  onSuccess: (order: Order) => void;
  onOpenRequirements: (order: Order) => void;
}

export const CheckoutModal: React.FC<CheckoutModalProps> = ({
  website,
  customPackageName,
  customAmount,
  onClose,
  onSuccess,
  onOpenRequirements,
}) => {
  const [customerName, setCustomerName] = useState('');
  const [customerEmail, setCustomerEmail] = useState('');
  const [customerPhone, setCustomerPhone] = useState('');
  const [businessName, setBusinessName] = useState('');
  const [requirementsNote, setRequirementsNote] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<'stripe' | 'direct'>('stripe');

  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [completedOrder, setCompletedOrder] = useState<Order | null>(null);
  const [stripeConfigured, setStripeConfigured] = useState(false);

  const websiteName = website ? website.name : customPackageName || 'Custom Website Development';
  const amount = website ? website.price : customAmount || 199;
  const currency = website?.currency || 'USD';

  useEffect(() => {
    fetchSettings().then((s) => {
      setStripeConfigured(Boolean(s.stripeEnabled && s.stripePublishableKey));
    });
  }, []);

  const handleStartCheckout = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!customerName.trim() || !customerEmail.trim() || !customerPhone.trim()) {
      setError('Please provide your name, email, and phone/WhatsApp number.');
      return;
    }

    try {
      setIsProcessing(true);
      setError(null);

      // 1. Call server backend to create verified session & order
      const sessionResult = await createCheckoutSession({
        websiteId: website?.id,
        websiteName,
        amount,
        customerName: customerName.trim(),
        customerEmail: customerEmail.trim(),
        customerPhone: customerPhone.trim(),
        businessName: businessName.trim(),
        requirementsNote: requirementsNote.trim(),
        paymentMethod,
      });

      // 2. If Stripe redirected checkout URL was generated by real Stripe API
      if (sessionResult.checkoutUrl && sessionResult.provider === 'stripe_checkout') {
        window.location.href = sessionResult.checkoutUrl;
        return;
      }

      // 3. Complete server-side verification
      const verifyResult = await verifyPayment({
        orderId: sessionResult.orderId,
        sessionId: sessionResult.sessionId,
        transactionToken: `tx_${Date.now()}`,
      });

      if (verifyResult.verified) {
        setCompletedOrder(verifyResult.order);
        onSuccess(verifyResult.order);
      } else {
        setError('Payment verification failed on the server. Please contact support.');
      }
    } catch (err: any) {
      setError(err.message || 'Payment processing error. Please try again.');
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/85 backdrop-blur-md overflow-y-auto animate-in fade-in duration-200">
      <div className="relative w-full max-w-xl bg-[#0c101c] border border-white/15 rounded-3xl shadow-2xl overflow-hidden my-8">
        {/* Top Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-[#0e1322]">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center">
              <ShieldCheck className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-white">Secure Checkout</h2>
              <span className="text-[10px] text-slate-400">256-Bit SSL Encrypted Server Verification</span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white bg-white/[0.05] hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Order Confirmed Screen */}
        {completedOrder ? (
          <div className="p-8 sm:p-10 space-y-6 text-center">
            <div className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto shadow-lg shadow-emerald-500/10">
              <CheckCircle className="w-8 h-8" />
            </div>

            <div>
              <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 inline-block mb-3">
                Payment Verified • Order #{completedOrder.id}
              </span>
              <h3 className="text-2xl font-black text-white tracking-tight">
                Thank You, {completedOrder.customerName}!
              </h3>
              <p className="text-xs sm:text-sm text-slate-300 mt-2 max-w-md mx-auto">
                Your order for <strong className="text-white font-semibold">{completedOrder.websiteName}</strong> (${completedOrder.amount} {completedOrder.currency}) has been confirmed.
              </p>
            </div>

            {/* Next Steps Card */}
            <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 text-left space-y-3">
              <div className="text-xs font-bold uppercase tracking-wider text-blue-400 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" />
                <span>Next Immediate Step: Submit Business Assets</span>
              </div>
              <p className="text-xs text-slate-300">
                To begin building and customizing your website, please submit your logo, business info, and requirements.
              </p>
            </div>

            {/* Action Buttons */}
            <div className="space-y-3 pt-2">
              <button
                onClick={() => {
                  onClose();
                  onOpenRequirements(completedOrder);
                }}
                className="w-full py-3.5 px-4 rounded-xl text-sm font-bold text-white bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 shadow-lg shadow-blue-500/25 transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                <span>Submit Website Requirements Now</span>
                <ArrowRight className="w-4 h-4" />
              </button>

              <a
                href={getWhatsAppUrl(`Hi Build My Website! I just completed Order #${completedOrder.id} for "${completedOrder.websiteName}".`)}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full py-2.5 px-4 rounded-xl text-xs font-semibold text-emerald-300 bg-emerald-500/10 hover:bg-emerald-500/15 border border-emerald-500/20 transition-all flex items-center justify-center gap-2"
              >
                <MessageCircle className="w-4 h-4" />
                <span>Chat With Our Team on WhatsApp</span>
              </a>
            </div>
          </div>
        ) : (
          /* Checkout Form */
          <form onSubmit={handleStartCheckout} className="p-6 sm:p-8 space-y-6">
            {error && (
              <div className="p-3.5 rounded-xl bg-red-500/10 border border-red-500/20 text-xs text-red-300 flex items-start gap-2">
                <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            {/* Order Summary Pill */}
            <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-between">
              <div>
                <span className="text-[11px] uppercase tracking-wider text-slate-400 font-semibold">Selected Website</span>
                <div className="text-base font-bold text-white">{websiteName}</div>
              </div>
              <div className="text-right">
                <span className="text-[11px] uppercase tracking-wider text-slate-400 font-semibold">Total Due</span>
                <div className="text-xl font-black text-white bg-gradient-to-r from-blue-400 to-indigo-300 bg-clip-text text-transparent">
                  ${amount} <span className="text-xs font-normal text-slate-300">{currency}</span>
                </div>
              </div>
            </div>

            {/* Customer Information */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                1. Your Contact Information
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">
                    Your Full Name *
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="John Doe"
                    value={customerName}
                    onChange={(e) => setCustomerName(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-white/[0.04] border border-white/10 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">
                    Email Address (For Order Access) *
                  </label>
                  <input
                    type="email"
                    required
                    placeholder="john@example.com"
                    value={customerEmail}
                    onChange={(e) => setCustomerEmail(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-white/[0.04] border border-white/10 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-blue-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">
                    WhatsApp / Phone Number *
                  </label>
                  <input
                    type="tel"
                    required
                    placeholder="+1 (555) 000-0000"
                    value={customerPhone}
                    onChange={(e) => setCustomerPhone(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-white/[0.04] border border-white/10 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">
                    Business Name (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Apex Digital Corp"
                    value={businessName}
                    onChange={(e) => setBusinessName(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-white/[0.04] border border-white/10 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-blue-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-300 mb-1">
                  Brief Requirements / Notes (Optional)
                </label>
                <textarea
                  rows={2}
                  placeholder="Any immediate instructions or special requests..."
                  value={requirementsNote}
                  onChange={(e) => setRequirementsNote(e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl bg-white/[0.04] border border-white/10 text-xs sm:text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-blue-500"
                />
              </div>
            </div>

            {/* Payment Method Selection */}
            <div className="space-y-3">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                2. Secure Payment Method
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setPaymentMethod('stripe')}
                  className={`p-3.5 rounded-xl border text-left transition-all flex items-center justify-between ${
                    paymentMethod === 'stripe'
                      ? 'bg-blue-500/10 border-blue-500 ring-1 ring-blue-500/40 text-white'
                      : 'bg-white/[0.02] border-white/10 text-slate-300 hover:border-white/20'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <CreditCard className="w-4 h-4 text-blue-400" />
                    <div>
                      <div className="text-xs font-bold">Credit / Debit Card</div>
                      <div className="text-[10px] text-slate-400">Visa, Mastercard, Amex</div>
                    </div>
                  </div>
                  {paymentMethod === 'stripe' && <CheckCircle className="w-4 h-4 text-blue-400" />}
                </button>

                <button
                  type="button"
                  onClick={() => setPaymentMethod('direct')}
                  className={`p-3.5 rounded-xl border text-left transition-all flex items-center justify-between ${
                    paymentMethod === 'direct'
                      ? 'bg-blue-500/10 border-blue-500 ring-1 ring-blue-500/40 text-white'
                      : 'bg-white/[0.02] border-white/10 text-slate-300 hover:border-white/20'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <Lock className="w-4 h-4 text-emerald-400" />
                    <div>
                      <div className="text-xs font-bold">Instant Verified Gateway</div>
                      <div className="text-[10px] text-slate-400">Direct server verified</div>
                    </div>
                  </div>
                  {paymentMethod === 'direct' && <CheckCircle className="w-4 h-4 text-blue-400" />}
                </button>
              </div>
            </div>

            {/* Submit Button */}
            <div className="pt-2">
              <button
                type="submit"
                disabled={isProcessing}
                className="w-full py-3.5 px-4 rounded-xl text-sm font-bold text-white bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 shadow-lg shadow-blue-500/25 transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {isProcessing ? (
                  <div className="flex items-center gap-2">
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    <span>Verifying Secure Payment...</span>
                  </div>
                ) : (
                  <>
                    <Lock className="w-4 h-4" />
                    <span>PAY NOW • ${amount} {currency}</span>
                  </>
                )}
              </button>

              <div className="text-center mt-3 text-[11px] text-slate-400 flex items-center justify-center gap-1.5">
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span>100% Satisfaction Guarantee • No Hidden Fees</span>
              </div>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};
